name: CI Pipeline

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: Instalação de Dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install uv
          uv pip install -r requirements.txt

      - name: Rodar Linter
        run: |
          source venv/bin/activate
          ruff check .
          ruff format --check .
          ruff format .
      
      - name: Rodar o Ruff format
        run: |
          source venv/bin/activate
          ruff format .

  build_and_test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: Instalação de Dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install uv
          uv pip install -r requirements.txt
    
      - name: Rodar testes
        run: |
          source venv/bin/activate
          echo "Diretório atual:" && pwd
          echo "Conteúdo do diretório:" && ls
          cd test && ls && pytest
